import Header from '@/components/Header'
import './globals.css'
import Providers from './Providers'

export const metadata = {
	title: 'TMDB Clone',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<Header />
					{/* Nave */}
					{/* Search */}
					{children}
				</Providers>
			</body>
		</html>
	)
}
