import Header from '@/components/Header'
import './globals.css'

export const metadata = {
	title: 'TMDB Clone',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<Header />
				{/* Nave */}
				{/* Search */}
				{children}
			</body>
		</html>
	)
}
