import Header from '@/components/Header'
import NaveBar from '@/components/NaveBar'
import Providers from './Providers'
import SearchBox from '@/components/SearchBox'

import './globals.css'
import Footer from '@/components/Footer'

export const metadata = {
	title: 'TMDB Clone',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<Header />
					<NaveBar />
					<SearchBox />
					<main className="flex-1">{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	)
}
